database:
  host: host.docker.internal
  port: 5432
  dbname: retail_dwh
  user: postgres
  password: 1907

paths:
  raw_data: /opt/airflow/data/raw_csv
  processed_tracking: /opt/airflow/data/processed_files.txt